version: '3.8'

services:
  gapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - ORIGIN=http://localhost:3000
      # Auth.js environment variables
      - AUTH_SECRET=${AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gapp-network

networks:
  gapp-network:
    driver: bridge