version: '3.8'

services:
  gapp-dev:
    build:
      context: .
      target: deps  # Stop at deps stage for development
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped